
on:
   workflow_dispatch

jobs:
   hello-world:
   runs-on: ubuntu-18.4
   steps:
      - run: echo 'hello world'

   hellow-world-python:
   runs-on: ubuntu-18.4
   steps:
      - run: print('hello world')
        shell: python
   
